### ISSUE TITLE
Setting to change the default selector in navbar search

### ISSUE THREAD

**Issue by whoamitty** [Crossoufire/MyLists#23]
Hello, I would like
an option to set in config for have book by default in the search tool
instead of the Media option

I prefer this because in my case, I consider books more important
Thanks a lot if you consider my request ❤️

**Comment by Crossoufire** [comment]
Hello,

I can do that yes, i will try to do it soon.

Best regards,
Vincent

________________________________
De : ALEXANDER Tyrese ***@***.***>
Envoyé : mercredi 27 novembre 2024 02:17
À : Crossoufire/MyLists ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [Crossoufire/MyLists] have book by default in the search tool (Issue #23)


Hello, I would like
an option to set in config for have book by default in the search tool
instead of the media option

I prefer this because in my case, I consider books more important

**Comment by Crossoufire** [comment]
It is done, i have added an option in the user settings in the the MediaList tab.
